const FETCH_MATCHES = 'MATCH/FETCH_MATCHES';
const ADD_MATCH = 'MATCH/ADD_MATCH';
const GET_WINRATE = 'MATCH/GET_WINRATE';
const FETCH_MATCHES_FOR_DATE = 'MATCH/FETCH_MATCHES_FOR_DATE';

module.exports = {
  FETCH_MATCHES, ADD_MATCH, GET_WINRATE, FETCH_MATCHES_FOR_DATE
}
