const HOKKEY2TIME_FETCH_MATCHES = 'MATCH/HOKKEY2TIME/FETCH_MATCHES';
const HOKKEY2TIME_GET_WINRATE = 'MATCH/HOKKEY2TIME/GET_WINRATE';
const HOKKEY2TIME_FETCH_MATCHES_FOR_DATE = 'MATCH/HOKKEY2TIME/FETCH_MATCHES_FOR_DATE';
const FOOTBALLSR_FETCH_MATCHES = 'MATCH/FOOTBALLSR/FETCH_MATCHES';
const FOOTBALLSR_FETCH_MATCHES_FOR_DATE = 'MATCH/FOOTBALLSR/FETCH_MATCHES_FOR_DATE';
const FOOTBALLSR_GET_WINRATE = 'MATCH/FOOTBALLSR/GET_WINRATE';
const ADD_MATCH = 'MATCH/ADD_MATCH';

module.exports = {
  HOKKEY2TIME_FETCH_MATCHES, ADD_MATCH, HOKKEY2TIME_GET_WINRATE, HOKKEY2TIME_FETCH_MATCHES_FOR_DATE,FOOTBALLSR_FETCH_MATCHES, FOOTBALLSR_FETCH_MATCHES_FOR_DATE, FOOTBALLSR_GET_WINRATE
}
